controller:
  service:
    type: NodePort
    nodePorts:
      http: 31080
      https: 31443
      tcp:
        8080: 31808

  admissionWebhooks:
    enabled: false

  metrics:
    port: 10254
    # if this port is changed, change healthz-port: in extraArgs: accordingly
    service:
      annotations: 
        prometheus.io/scrape: "true"
        prometheus.io/port: "10254"

    serviceMonitor:
      additionalLabels:
        release: prometheus-stack
  ingressClassResource:
    name: nginx-second
    enabled: true
    default: false
    controllerValue: "k8s.io/ingress-nginx-second"
