

grafana:
  enabled: false


## Deploy a Prometheus instance
##
prometheus:

  ingress:
    enabled: true

    ingressClassName: nginx

    hosts: 
    - prometheus.example.com

    paths: 
    - /

    pathType: Prefix
  
  ## Settings affecting prometheusSpec
  ## ref: https://github.com/prometheus-operator/prometheus-operator/blob/main/Documentation/api.md#prometheusspec
  ##
  prometheusSpec:

    ## How long to retain metrics
    ##
    retention: 14d

    ## Number of replicas of each shard to deploy for a Prometheus deployment.
    ## Number of replicas multiplied by shards is the total number of Pods created.
    ##
    replicas: 2

    ## Resource limits & requests
    ##
    resources:
      limits:
        cpu: 500m
        memory: 900Mi
      requests:
        cpu: 200m
        memory: 600Mi

    ## Prometheus StorageSpec for persistent data
    ## ref: https://github.com/prometheus-operator/prometheus-operator/blob/main/Documentation/user-guides/storage.md
    ##
    storageSpec: 
      volumeClaimTemplate:
        spec:
          storageClassName: gp2
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 20Gi
